//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Autokar
{
    public decimal Id_autokaru { get; set; }
    public decimal Id_kursu { get; set; }
    public string Nr_rejestr { get; set; }
    public string Marka { get; set; }
    public string Model { get; set; }
    public Nullable<decimal> Liczba_miejsc { get; set; }

    public virtual Kurs Kurs { get; set; }
}

public partial class Kierowca
{
    public decimal Id_kierowcy { get; set; }
    public Nullable<decimal> Id_kursu { get; set; }
    public string Imie_Nazwisko { get; set; }

    public virtual Kurs Kurs { get; set; }
}

public partial class Kurs
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Kurs()
    {
        this.Autokar = new HashSet<Autokar>();
        this.Kierowca = new HashSet<Kierowca>();
    }

    public decimal Id_kursu { get; set; }
    public decimal Id_trasy { get; set; }
    public string Oznaczenie { get; set; }
    public Nullable<System.DateTime> Data_kursu { get; set; }
    public Nullable<decimal> Ilość_pasażerów { get; set; }
    public Nullable<System.TimeSpan> Godzina_rozpoczecia { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Autokar> Autokar { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Kierowca> Kierowca { get; set; }
    public virtual Trasa Trasa { get; set; }
}

public partial class Miejscowości
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Miejscowości()
    {
        this.Przebieg = new HashSet<Przebieg>();
        this.Trasa = new HashSet<Trasa>();
        this.Trasa1 = new HashSet<Trasa>();
    }

    public decimal Id_miejscowosci { get; set; }
    public string Nazwa_miejscowosci { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Przebieg> Przebieg { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Trasa> Trasa { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Trasa> Trasa1 { get; set; }
}

public partial class Przebieg
{
    public decimal Id_przebiegu { get; set; }
    public decimal Id_miejscowosci { get; set; }
    public decimal Id_trasy { get; set; }
    public Nullable<System.TimeSpan> Roznica_czasu { get; set; }
    public Nullable<decimal> Kolejnosc { get; set; }

    public virtual Miejscowości Miejscowości { get; set; }
    public virtual Trasa Trasa { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class Trasa
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Trasa()
    {
        this.Kurs = new HashSet<Kurs>();
        this.Przebieg = new HashSet<Przebieg>();
    }

    public decimal Id_trasy { get; set; }
    public decimal Id_miejscowosci_poczatek { get; set; }
    public decimal Id_miejscowosci_koniec { get; set; }
    public string Oznaczenie_trasy { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Kurs> Kurs { get; set; }
    public virtual Miejscowości Miejscowości { get; set; }
    public virtual Miejscowości Miejscowości1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Przebieg> Przebieg { get; set; }
}
