//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza_PKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autokar
    {
        public decimal Id_autokaru { get; set; }
        public decimal Id_kursu { get; set; }
        public string Nr_rejestr { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> Liczba_miejsc { get; set; }
    
        public virtual Kurs Kurs { get; set; }
    }
}
