//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza_PKS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Baza_PKSEntities : DbContext
    {
        public Baza_PKSEntities()
            : base("name=Baza_PKSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Autokar> Autokar { get; set; }
        public DbSet<Kierowca> Kierowca { get; set; }
        public DbSet<Kurs> Kurs { get; set; }
        public DbSet<Miejscowości> Miejscowości { get; set; }
        public DbSet<Przebieg> Przebieg { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Trasa> Trasa { get; set; }
    }
}
