//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza_PKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kierowca
    {
        public decimal Id_kierowcy { get; set; }
        public Nullable<decimal> Id_kursu { get; set; }
        public string Imie_Nazwisko { get; set; }
    
        public virtual Kurs Kurs { get; set; }
    }
}
