//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza_PKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurs
    {
        public Kurs()
        {
            this.Autokar = new HashSet<Autokar>();
            this.Kierowca = new HashSet<Kierowca>();
        }
    
        public decimal Id_kursu { get; set; }
        public decimal Id_trasy { get; set; }
        public string Oznaczenie { get; set; }
        public Nullable<System.DateTime> Data_kursu { get; set; }
        public Nullable<decimal> Ilość_pasażerów { get; set; }
        public Nullable<System.TimeSpan> Godzina_rozpoczecia { get; set; }
    
        public virtual ICollection<Autokar> Autokar { get; set; }
        public virtual ICollection<Kierowca> Kierowca { get; set; }
        public virtual Trasa Trasa { get; set; }
    }
}
