//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza_PKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miejscowości
    {
        public Miejscowości()
        {
            this.Przebieg = new HashSet<Przebieg>();
            this.Trasa = new HashSet<Trasa>();
            this.Trasa1 = new HashSet<Trasa>();
        }
    
        public decimal Id_miejscowosci { get; set; }
        public string Nazwa_miejscowosci { get; set; }
    
        public virtual ICollection<Przebieg> Przebieg { get; set; }
        public virtual ICollection<Trasa> Trasa { get; set; }
        public virtual ICollection<Trasa> Trasa1 { get; set; }
    }
}
