//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza_PKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przebieg
    {
        public decimal Id_przebiegu { get; set; }
        public decimal Id_miejscowosci { get; set; }
        public decimal Id_trasy { get; set; }
        public Nullable<System.TimeSpan> Roznica_czasu { get; set; }
        public Nullable<decimal> Kolejnosc { get; set; }
    
        public virtual Miejscowości Miejscowości { get; set; }
        public virtual Trasa Trasa { get; set; }
    }
}
